services:
    meetzy_backend:
        container_name: meetzy_backend
        user: "1000:1000"
        image: gitlab.restricted.digital:5050/johnj/meetzy/meetzy_backend:${TAG_NAME}
        build:
            context: .
            target: meetzy_backend
        volumes:
            - './:/opt/meetzy/'
            - './.docker/supervisor/conf.d:/etc/supervisor/conf.d'
            - './.docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            COUNTRIES_JSON: "countries.json"
            CITIES_JSON: "cities.json"
        networks:
            - meetzy_network
        ports:
            - '8080:8080'
        dns:
            - 8.8.8.8
            - 4.4.4.4

    meetzy_web_server:
        container_name: meetzy_web_server
        image: gitlab.restricted.digital:5050/johnj/meetzy/meetzy_web_server:${TAG_NAME}
        build:
            context: .
            target: meetzy_web_server
        ports:
            - '${DEPLOY_PORT}:80'
        environment:
            FPM_HOST: "meetzy_backend:9000"
            WEBSOCKET_HOST: "meetzy_backend:8080"
        volumes:
            - './public:/opt/meetzy/public'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - meetzy_network
        tty: true

    meetzy_redis:
        container_name: meetzy_redis
        image: 'redis:7.2.4-alpine'
        ports:
            - '8307:6379'
        networks:
            - meetzy_network

    meetzy_database:
        image: 'mariadb:latest'
        container_name: meetzy_database
        ports:
            - '8306:3306'
        environment:
            MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ROOT_HOST: '%'
            MARIADB_DATABASE: '${DB_DATABASE}'
            MARIADB_USER: '${DB_USERNAME}'
            MARIADB_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
        volumes:
            - meetzy-database:/var/lib/mysql/
        networks:
            - meetzy_network

    meetzy_mailhog:
        container_name: meetzy_mailhog
        image: 'mailhog/mailhog'
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - meetzy_network

    meetzy_elasticsearch:
        container_name: meetzy_elasticsearch
        image: 'docker.elastic.co/elasticsearch/elasticsearch:8.15.3'
        ports:
            - '9200:9200'
            - '9300:9300'
        environment:
            discovery.type: single-node
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
            ELASTIC_PASSWORD: '${ELASTIC_PASSWORD}'
            xpack.security.enabled: true
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
            - elasticsearch-config:/usr/share/elasticsearch/config
        networks:
            - meetzy_network

    meetzy_kibana:
        container_name: meetzy_kibana
        image: 'docker.elastic.co/kibana/kibana:8.15.3'
        ports:
            - '6601:5601'
        environment:
            ELASTICSEARCH_HOSTS: "http://meetzy_elasticsearch:9200"
            ELASTICSEARCH_SERVICEACCOUNTTOKEN: 'AAEAAWVsYXN0aWMva2liYW5hL21lZXR6eV9raWJhbmFfdG9rZW46TFB1R1l4LUlSMTJSQWhLWGxvNzlYUQ'
        networks:
            - meetzy_network

networks:
    meetzy_network:
volumes:
    meetzy-database:
        driver: local
    elasticsearch-data:
        driver: local
    elasticsearch-config:
        driver: local
